# **Tutorial 1: Creating DataArrays and Datasets to Assess Global Climate Data**


**Week 1, Day 1, Climate System Overview**

**Content creators:** Sloane Garelick, Julia Kent

**Content reviewers:** Yosmely Bermúdez, Katrina Dobson, Younkap Nina Duplex, Danika Gupta, Maria Gonzalez, Will Gregory, Nahid Hasan, Sherry Mi, Beatriz Cosenza Muralles, Jenna Pearson, Chi Zhang, Ohad Zivan 

**Content editors:** Jenna Pearson, Chi Zhang, Ohad Zivan 

**Production editors:** Wesley Banfield, Jenna Pearson, Chi Zhang, Ohad Zivan

**Our 2023 Sponsors:** NASA TOPS

# **Tutorial Objectives**


As you just learned in the Introduction to Climate video, variations in global climate involve various forcings, feedbacks, and interactions between multiple processes and systems. Because of this complexity, global climate datasets are often very large with multiple dimensions and variables.

One useful computational tool for organizing, analyzing and interpreting large global datasets is XArray, an open source project and Python package that makes working with labelled multi-dimensional arrays simple and efficient.

In this first tutorial, we will use the `DataArray` and `Dataset` objects, which are used to represent and manipulate spatial data, to practice organizing large global climate datasets and to understand variations in Earth's climate system.

# Setup

Similar to `numpy`, `np`; `pandas`, `pd`; you may often encounter `xarray` imported within a shortened namespace as `xr`.

In [1]:
# !pip install numpy
# !pip install pandas
# !pip install xarray

In [2]:
# imports
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt

In [3]:
# @title Figure Settings
import ipywidgets as widgets       # interactive display
%config InlineBackend.figure_format = 'retina'
plt.style.use("https://raw.githubusercontent.com/ClimateMatchAcademy/course-content/main/cma.mplstyle")

In [4]:
# @title Video 1: Video Title
#Tech team will add code to format and display the video

# Introducing the `DataArray` and `Dataset`

[Xarray](https://xarray.pydata.org/en/v2023.05.0/getting-started-guide/why-xarray.html) expands on the capabilities on [NumPy](https://numpy.org/doc/stable/user/index.html#user) arrays, providing a lot of streamlined data manipulation. It is similar in that respect to [Pandas](https://pandas.pydata.org/docs/user_guide/index.html#user-guide), but whereas Pandas excels at working with tabular data, Xarray is focused on N-dimensional arrays of data (i.e. grids). Its interface is based largely on the netCDF data model (variables, attributes, and dimensions), but it goes beyond the traditional netCDF interfaces to provide functionality similar to netCDF-java's [Common Data Model (CDM)](https://docs.unidata.ucar.edu/netcdf-java/current/userguide/common_data_model_overview.html). 

# Section 1: Creation of a `DataArray` object

The `DataArray` is one of the basic building blocks of Xarray (see docs [here](http://xarray.pydata.org/en/stable/user-guide/data-structures.html#dataarray)). It provides a `numpy.ndarray`-like object that expands to provide two critical pieces of functionality:

1. Coordinate names and values are stored with the data, making slicing and indexing much more powerful
2. It has a built-in container for attributes

Here we'll initialize a `DataArray` object by wrapping a plain NumPy array, and explore a few of its properties.

## Section 1.1: Generate a random numpy array

For our first example, we'll just create a random array of "temperature" data in units of Kelvin:

In [5]:
rand_data = 283 + 5 * np.random.randn(5, 3, 4)
rand_data

array([[[285.14505626, 282.00773468, 283.03015868, 284.68931859],
        [281.38951645, 281.99172052, 274.46821087, 275.54227954],
        [283.02691635, 283.88945356, 279.79996974, 289.40569675]],

       [[284.89588573, 285.54163213, 280.74929664, 282.32384663],
        [288.86944866, 286.83055073, 277.76977178, 283.15193592],
        [288.913082  , 291.84220683, 289.42006343, 283.83557337]],

       [[282.57298715, 284.68790176, 279.23541985, 268.53584275],
        [284.52633911, 281.74305949, 282.2942012 , 282.98836786],
        [279.1060261 , 277.83429426, 277.32713625, 279.85020276]],

       [[278.54924384, 275.87772339, 283.84235294, 273.67132137],
        [280.25024697, 282.41186306, 281.30093383, 292.72131134],
        [288.3293155 , 281.52758925, 280.66006612, 283.04905769]],

       [[287.33443835, 280.7661887 , 274.88343719, 290.35364495],
        [280.60461493, 284.23430127, 289.12206553, 283.47481961],
        [286.21027958, 277.8480345 , 289.76363591, 276.42016731]]])

## Section 1.2: Wrap the array: first attempt

Now we create a basic `DataArray` just by passing our plain `data` as input:

In [6]:
temperature = xr.DataArray(rand_data)
temperature

<xarray.DataArray (dim_0: 5, dim_1: 3, dim_2: 4)>
array([[[285.14505626, 282.00773468, 283.03015868, 284.68931859],
        [281.38951645, 281.99172052, 274.46821087, 275.54227954],
        [283.02691635, 283.88945356, 279.79996974, 289.40569675]],

       [[284.89588573, 285.54163213, 280.74929664, 282.32384663],
        [288.86944866, 286.83055073, 277.76977178, 283.15193592],
        [288.913082  , 291.84220683, 289.42006343, 283.83557337]],

       [[282.57298715, 284.68790176, 279.23541985, 268.53584275],
        [284.52633911, 281.74305949, 282.2942012 , 282.98836786],
        [279.1060261 , 277.83429426, 277.32713625, 279.85020276]],

       [[278.54924384, 275.87772339, 283.84235294, 273.67132137],
        [280.25024697, 282.41186306, 281.30093383, 292.72131134],
        [288.3293155 , 281.52758925, 280.66006612, 283.04905769]],

       [[287.33443835, 280.7661887 , 274.88343719, 290.35364495],
        [280.60461493, 284.23430127, 289.12206553, 283.47481961],
        [286.21027958, 277.8480345 , 289.76363591, 276.42016731]]])
Dimensions without coordinates: dim_0, dim_1, dim_2

Note two things:

1. Xarray generates some basic dimension names for us (`dim_0`, `dim_1`, `dim_2`). We'll improve this with better names in the next example.
2. Wrapping the numpy array in a `DataArray` gives us a rich display in the notebook! (Try clicking the array symbol to expand or collapse the view)

## Section 1.3: Assign dimension names

Much of the power of Xarray comes from making use of named dimensions. So let's add some more useful names! We can do that by passing an ordered list of names using the keyword argument `dims`:

In [7]:
temperature = xr.DataArray(rand_data, dims=['time', 'lat', 'lon'])
temperature

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[285.14505626, 282.00773468, 283.03015868, 284.68931859],
        [281.38951645, 281.99172052, 274.46821087, 275.54227954],
        [283.02691635, 283.88945356, 279.79996974, 289.40569675]],

       [[284.89588573, 285.54163213, 280.74929664, 282.32384663],
        [288.86944866, 286.83055073, 277.76977178, 283.15193592],
        [288.913082  , 291.84220683, 289.42006343, 283.83557337]],

       [[282.57298715, 284.68790176, 279.23541985, 268.53584275],
        [284.52633911, 281.74305949, 282.2942012 , 282.98836786],
        [279.1060261 , 277.83429426, 277.32713625, 279.85020276]],

       [[278.54924384, 275.87772339, 283.84235294, 273.67132137],
        [280.25024697, 282.41186306, 281.30093383, 292.72131134],
        [288.3293155 , 281.52758925, 280.66006612, 283.04905769]],

       [[287.33443835, 280.7661887 , 274.88343719, 290.35364495],
        [280.60461493, 284.23430127, 289.12206553, 283.47481961],
        [286.21027958, 277.8480345 , 289.76363591, 276.42016731]]])
Dimensions without coordinates: time, lat, lon

This is already an improvement over a NumPy array because we have names for each of the dimensions (or axes). Even better, we can associate arrays representing the values for the coordinates for each of these dimensions with the data when we create the `DataArray`. We'll see this in the next example.

# Section 2: Create a `DataArray` with named Coordinates

## Section 2.1: Make time and space coordinates

Here we will use [Pandas](https://foundations.projectpythia.org/core/pandas.html) to create an array of [datetime data](https://foundations.projectpythia.org/core/datetime.html), which we will then use to create a `DataArray` with a named coordinate `time`.

In [8]:
times_index = pd.date_range('2018-01-01', periods=5)
times_index

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

We'll also create arrays to represent sample longitude and latitude:

In [9]:
lons = np.linspace(-120, -60, 4)
lats = np.linspace(25, 55, 3)

### Section 2.1.1: Initialize the `DataArray` with complete coordinate info

When we create the `DataArray` instance, we pass in the arrays we just created:

In [10]:
temperature = xr.DataArray(rand_data, coords=[times_index, lats, lons], dims=['time', 'lat', 'lon'])
temperature

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[285.14505626, 282.00773468, 283.03015868, 284.68931859],
        [281.38951645, 281.99172052, 274.46821087, 275.54227954],
        [283.02691635, 283.88945356, 279.79996974, 289.40569675]],

       [[284.89588573, 285.54163213, 280.74929664, 282.32384663],
        [288.86944866, 286.83055073, 277.76977178, 283.15193592],
        [288.913082  , 291.84220683, 289.42006343, 283.83557337]],

       [[282.57298715, 284.68790176, 279.23541985, 268.53584275],
        [284.52633911, 281.74305949, 282.2942012 , 282.98836786],
        [279.1060261 , 277.83429426, 277.32713625, 279.85020276]],

       [[278.54924384, 275.87772339, 283.84235294, 273.67132137],
        [280.25024697, 282.41186306, 281.30093383, 292.72131134],
        [288.3293155 , 281.52758925, 280.66006612, 283.04905769]],

       [[287.33443835, 280.7661887 , 274.88343719, 290.35364495],
        [280.60461493, 284.23430127, 289.12206553, 283.47481961],
        [286.21027958, 277.8480345 , 289.76363591, 276.42016731]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

### Section 2.1.2: Set useful attributes

We can also set some attribute metadata, which will help provide clear descriptions of the data. In this case, we can specify that we're looking at 'air_temperature' data and the units are 'kelvin'.

In [11]:
temperature.attrs['units'] = 'kelvin'
temperature.attrs['standard_name'] = 'air_temperature'

temperature

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[285.14505626, 282.00773468, 283.03015868, 284.68931859],
        [281.38951645, 281.99172052, 274.46821087, 275.54227954],
        [283.02691635, 283.88945356, 279.79996974, 289.40569675]],

       [[284.89588573, 285.54163213, 280.74929664, 282.32384663],
        [288.86944866, 286.83055073, 277.76977178, 283.15193592],
        [288.913082  , 291.84220683, 289.42006343, 283.83557337]],

       [[282.57298715, 284.68790176, 279.23541985, 268.53584275],
        [284.52633911, 281.74305949, 282.2942012 , 282.98836786],
        [279.1060261 , 277.83429426, 277.32713625, 279.85020276]],

       [[278.54924384, 275.87772339, 283.84235294, 273.67132137],
        [280.25024697, 282.41186306, 281.30093383, 292.72131134],
        [288.3293155 , 281.52758925, 280.66006612, 283.04905769]],

       [[287.33443835, 280.7661887 , 274.88343719, 290.35364495],
        [280.60461493, 284.23430127, 289.12206553, 283.47481961],
        [286.21027958, 277.8480345 , 289.76363591, 276.42016731]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

### Section 2.1.3: Attributes are not preserved by default!

Notice what happens if we perform a mathematical operaton with the `DataArray`: the coordinate values persist, but the attributes are lost. This is done because it is very challenging to know if the attribute metadata is still correct or appropriate after arbitrary arithmetic operations.

To illustrate this, we'll do a simple unit conversion from Kelvin to Celsius:

In [12]:
temperature_in_celsius = temperature - 273.15
temperature_in_celsius

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[11.99505626,  8.85773468,  9.88015868, 11.53931859],
        [ 8.23951645,  8.84172052,  1.31821087,  2.39227954],
        [ 9.87691635, 10.73945356,  6.64996974, 16.25569675]],

       [[11.74588573, 12.39163213,  7.59929664,  9.17384663],
        [15.71944866, 13.68055073,  4.61977178, 10.00193592],
        [15.763082  , 18.69220683, 16.27006343, 10.68557337]],

       [[ 9.42298715, 11.53790176,  6.08541985, -4.61415725],
        [11.37633911,  8.59305949,  9.1442012 ,  9.83836786],
        [ 5.9560261 ,  4.68429426,  4.17713625,  6.70020276]],

       [[ 5.39924384,  2.72772339, 10.69235294,  0.52132137],
        [ 7.10024697,  9.26186306,  8.15093383, 19.57131134],
        [15.1793155 ,  8.37758925,  7.51006612,  9.89905769]],

       [[14.18443835,  7.6161887 ,  1.73343719, 17.20364495],
        [ 7.45461493, 11.08430127, 15.97206553, 10.32481961],
        [13.06027958,  4.6980345 , 16.61363591,  3.27016731]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

We usually wish to keep metadata with our dataset, even after manipulating the data. For example it can tell us what the units are of a variable of interest. So when you perform operations on your data, make sure to check that all the information you want is carried over. If it isn't, you can add it back in following the instructions in the section before this. For an in-depth discussion of how Xarray handles metadata, start in the Xarray docs [here](http://xarray.pydata.org/en/stable/getting-started-guide/faq.html#approach-to-metadata).

# Section 3: The `Dataset`: a container for `DataArray`s with shared coordinates

Along with `DataArray`, the other key object type in Xarray is the `Dataset`, which is a dictionary-like container that holds one or more `DataArray`s, which can also optionally share coordinates (see docs [here](http://xarray.pydata.org/en/stable/user-guide/data-structures.html#dataset)).

The most common way to create a `Dataset` object is to load data from a file (which we will practice in a later tutorial). Here, instead, we will create another `DataArray` and combine it with our `temp` data.

This will illustrate how the information about common coordinate axes is used.

## Section 3.1: Create a pressure `DataArray` using the same coordinates

This code mirrors how we created the `temperature` object above.

In [13]:
pressure_data = 1000.0 + 5 * np.random.randn(5, 3, 4)
pressure = xr.DataArray(
    pressure_data, coords=[times_index, lats, lons], dims=['time', 'lat', 'lon']
)
pressure.attrs['units'] = 'hPa'
pressure.attrs['standard_name'] = 'air_pressure'

pressure

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[ 997.42614254,  991.98198556,  992.84007105,  997.08100966],
        [1001.43904477,  999.9648856 , 1001.0313747 ,  998.87529978],
        [ 999.70559619, 1002.17603692, 1007.46167335, 1002.21851289]],

       [[ 994.0213541 , 1006.56671003, 1011.46448225, 1006.02469796],
        [ 998.60241472, 1007.27112148, 1002.09132089,  996.93348908],
        [ 995.61960133, 1000.16916301, 1001.62327408,  997.89725573]],

       [[1005.73091145,  993.22506935,  999.26426433,  996.84828064],
        [1002.46183568, 1011.49149595, 1001.37096229, 1006.0502618 ],
        [ 998.88145054, 1002.57586818,  996.85640675,  989.47301137]],

       [[ 994.91110407, 1005.07118168, 1005.30596944, 1003.03810319],
        [1004.40818211, 1001.24340233,  992.70120321, 1002.32754331],
        [1000.77298415,  999.99452019, 1003.86294691, 1004.20071984]],

       [[1006.44566197,  995.29358167,  995.22426689,  992.57816046],
        [1000.9377338 , 1011.13318897, 1002.66448735,  996.5877688 ],
        [ 993.1961186 , 1001.66372587, 1004.98333844,  989.93488554]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

## Section 3.2: Create a `Dataset` object

Each `DataArray` in our `Dataset` needs a name! 

The most straightforward way to create a `Dataset` with our `temperature` and `pressure` arrays is to pass a dictionary using the keyword argument `data_vars`:

In [14]:
ds = xr.Dataset(data_vars={'Temperature': temperature, 'Pressure': pressure})
ds

<xarray.Dataset>
Dimensions:      (time: 5, lat: 3, lon: 4)
Coordinates:
  * time         (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat          (lat) float64 25.0 40.0 55.0
  * lon          (lon) float64 -120.0 -100.0 -80.0 -60.0
Data variables:
    Temperature  (time, lat, lon) float64 285.1 282.0 283.0 ... 289.8 276.4
    Pressure     (time, lat, lon) float64 997.4 992.0 992.8 ... 1.005e+03 989.9

Notice that the `Dataset` object `ds` is aware that both data arrays sit on the same coordinate axes.

## Section 3.3: Access Data variables and Coordinates in a `Dataset`

We can pull out any of the individual `DataArray` objects in a few different ways.

Using the "dot" notation:

In [15]:
ds.Pressure

<xarray.DataArray 'Pressure' (time: 5, lat: 3, lon: 4)>
array([[[ 997.42614254,  991.98198556,  992.84007105,  997.08100966],
        [1001.43904477,  999.9648856 , 1001.0313747 ,  998.87529978],
        [ 999.70559619, 1002.17603692, 1007.46167335, 1002.21851289]],

       [[ 994.0213541 , 1006.56671003, 1011.46448225, 1006.02469796],
        [ 998.60241472, 1007.27112148, 1002.09132089,  996.93348908],
        [ 995.61960133, 1000.16916301, 1001.62327408,  997.89725573]],

       [[1005.73091145,  993.22506935,  999.26426433,  996.84828064],
        [1002.46183568, 1011.49149595, 1001.37096229, 1006.0502618 ],
        [ 998.88145054, 1002.57586818,  996.85640675,  989.47301137]],

       [[ 994.91110407, 1005.07118168, 1005.30596944, 1003.03810319],
        [1004.40818211, 1001.24340233,  992.70120321, 1002.32754331],
        [1000.77298415,  999.99452019, 1003.86294691, 1004.20071984]],

       [[1006.44566197,  995.29358167,  995.22426689,  992.57816046],
        [1000.9377338 , 1011.13318897, 1002.66448735,  996.5877688 ],
        [ 993.1961186 , 1001.66372587, 1004.98333844,  989.93488554]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

... or using dictionary access like this:

In [16]:
ds['Pressure']

<xarray.DataArray 'Pressure' (time: 5, lat: 3, lon: 4)>
array([[[ 997.42614254,  991.98198556,  992.84007105,  997.08100966],
        [1001.43904477,  999.9648856 , 1001.0313747 ,  998.87529978],
        [ 999.70559619, 1002.17603692, 1007.46167335, 1002.21851289]],

       [[ 994.0213541 , 1006.56671003, 1011.46448225, 1006.02469796],
        [ 998.60241472, 1007.27112148, 1002.09132089,  996.93348908],
        [ 995.61960133, 1000.16916301, 1001.62327408,  997.89725573]],

       [[1005.73091145,  993.22506935,  999.26426433,  996.84828064],
        [1002.46183568, 1011.49149595, 1001.37096229, 1006.0502618 ],
        [ 998.88145054, 1002.57586818,  996.85640675,  989.47301137]],

       [[ 994.91110407, 1005.07118168, 1005.30596944, 1003.03810319],
        [1004.40818211, 1001.24340233,  992.70120321, 1002.32754331],
        [1000.77298415,  999.99452019, 1003.86294691, 1004.20071984]],

       [[1006.44566197,  995.29358167,  995.22426689,  992.57816046],
        [1000.9377338 , 1011.13318897, 1002.66448735,  996.5877688 ],
        [ 993.1961186 , 1001.66372587, 1004.98333844,  989.93488554]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

We'll return to the `Dataset` object when we start loading data from files in later tutorials today.

# Summary

In this initial tutorial, the `DataArray` and `Dataset` objects were utilized to create and explore synthetic examples of climate data.

# Resources

Code and data for this tutorial is based on existing content from [Project Pythia](https://foundations.projectpythia.org/core/xarray/xarray-intro.html).